namespace AsuntosPenalesAPI.Model.ViewModels.Enums
{
    public enum EnumEstadoProcesal
    {

        ACTIVO = 1,
        EN_ESTUDIO = 2,
        REMITIDO = 3,
        CONCLUIDO_REMITIDO = 4,
        PROCEDENTE = 5, 
        CONCLUIDO_POR_IMPROCEDENCIA = 6, 
        INVESTIGACION_INICIAL = 7,
        CONCLUIDO_POR_FACULTAD_DE_ABSTENERSE_DE_INVESTIGAR = 8,
        CONCLUIDO_POR_ARCHIVO_TEMPORAL = 9,
        CONCLUIDO_POR_NO_EJERCICIO_DE_LA_ACCION_PENAL = 10,
        CONCLUIDO_POR_ACUERDO_REPARATORIO = 11,
        CONCLUIDO_POR_CRITERIO_DE_OPORTUNIDAD = 12,
        INVESTIGACION_COMPLEMENTARIA = 13,
        ETAPA_INTERMEDIA = 14,
        CONCLUIDO_POR_SENTENCIA_CONDENATORIA_EN_PROCEDIMIENTO_ABREVIADO = 15,
        CONCLUIDO_POR_SOBRESEIMIENTO = 16,
        CONCLUIDO_POR_SUSPENSIÓN_CONDICIONAL_DEL_PROCESO = 17,
        ETAPA_JUICIO = 18,
        CONCLUIDO_POR_SENTENCIA_CONDENATORIA = 19,
        CONCLUIDO_POR_SENTENCIA_ABSOLUTORIA = 20,
        SENTENCIA = 21,
        RESUELTO = 22, 
        EN_REPARACION = 23, 
    }
}